version: 3

services:

  loki:
    image: grafana/loki
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail
    volumes:
      - ./configs/promtail/config.yml:/etc/promtail/config.yml:z
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana
    volumes:
      - ./configs/grafana/grafana.ini:/etc/grafana/grafana.ini:z
      - ./configs/grafana:/etc/grafana/provisioning:z
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: false
    ports:
      - 3000:3000

  escriba-server:
    image: mycloudlab/escriba-server
    ports:
      - 8888:8888
    environment:
      #TZ: America/Sao_Paulo
      LOGSERVER_SOURCEMAPS_ALLOWED_DOMAINS: http://localhost:8080
  demo:
    image: node:18-alpine
    volumes:
      - ./demo:/demo:z
    entrypoint: /bin/sh
    command: -c "cd /demo; npm i; npm run app"
    ports:
      - 8080:8080
