version: 3

services:
  loki:
    image: grafana/loki
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail
    volumes:
      - ./dev-assets/promtail/config.yml:/etc/promtail/config.yml:z
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

  jslog:
    hostname: jslog
    build: ./jslog
    context: ./jslog
    command: "/bin/bash -c 'trap : TERM INT; sleep infinity & wait'"
    environment:
      TZ: America/Sao_Paulo
    volumes:
      - ./jslog:/jslog:z

  jslog-angular:
    hostname: jslog-angular
    build: ./jslog-angular
    context: ./jslog-angular
    command: "/bin/bash -c 'trap : TERM INT; sleep infinity & wait'"
    environment:
      TZ: America/Sao_Paulo
    volumes:
      - ./jslog-angular:/jslog-angular:z


  log-server:
    hostname: log-server
    build: ./log-server
    context: ./log-server
    command: "/bin/bash -c 'trap : TERM INT; sleep infinity & wait'"
    environment:
      TZ: America/Sao_Paulo
    volumes:
      - ./dev-assets/maven/settings.xml:/usr/share/maven/conf/settings.xml:z
      - ./tmp/mvn:/.m2/repository:z
      - ./log-server:/log-server:z
    ports:
      - 8787:8787 # debug java port
      - 8888:8888

  grafana:
    image: grafana/grafana
    volumes:
      - ./dev-assets/grafana/grafana.ini:/etc/grafana/grafana.ini:z
      - ./dev-assets/grafana:/etc/grafana/provisioning:z
    environment:
      TZ: America/Sao_Paulo
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: false
    ports:
      - 3000:3000