version: 3

services:

  loki:
    image: grafana/loki
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail
    volumes:
      - ./dev-assets/promtail/config.yml:/etc/promtail/config.yml:z
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana
    volumes:
      - ./dev-assets/grafana/grafana.ini:/etc/grafana/grafana.ini:z
      - ./dev-assets/grafana:/etc/grafana/provisioning:z
    environment:
      TZ: America/Sao_Paulo
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: false
    ports:
      - 3000:3000

  escriba-server:
    image: mycloudlabs/escriba-server
    environment:
      TZ: America/Sao_Paulo

  demo:
    image: mycloudlabs/escriba-demo
    environment:
      TZ: America/Sao_Paulo