apiVersion: 1
deleteDatasources:
  - name: Loki
    orgId: 1

datasources:
- name: Loki
  type: loki
  access: proxy
  orgId: 1
  url: http://loki:3100
  password:
  user:
  database:
  version: 1
  editable: true