apiVersion: 1
deleteDatasources:
  - name: Jaeger
    orgId: 1

datasources:
- name: Jaeger
  type: jaeger
  access: proxy
  orgId: 1
  url: http://jaeger:16686
  password:
  user:
  database:
  version: 1
  editable: true