name: Continuous Delivery 

on:  
  push:
    tags:
      - '*'

jobs:  
  delivery-escriba-server:
    runs-on: ubuntu-latest
    environment: production
    name: compile build and push image mycloudlab/escriba-server
    steps:

      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          scope: '@mycloudlab'
      - run: |
          cd escriba-browser
          ls -lah
          npm run build
          npm version ${GITHUB_REF/refs\/tags\//}
          npm publish --public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push to Docker Hub
        run: |
          cd escriba-server
          docker build --file src/main/docker/Dockerfile.builder --tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/mycloudlab/escriba-server:latest .
          docker tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/mycloudlab/escriba-server:latest ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/mycloudlab/escriba-server:${GITHUB_REF/refs\/tags\//}
          docker push ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/mycloudlab/escriba-server
          docker push ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/mycloudlab/escriba-server:${GITHUB_REF/refs\/tags\//}
