name: Continuous Delivery 

on:  
  push:
    tags:
      - '*'

jobs:  
  delivery-escriba-server:
    runs-on: ubuntu-latest
    name: compile build and push image mycloudlab/escriba-server
    steps:

      - name: Get tag name
        id: get_tag_name
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Checkout the code
        uses: actions/checkout@v1
        with:
          ref: ${{ steps.get_tag_name.outputs.VERSION }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push to Docker Hub
        run: |
          cd escriba-server
          docker build --file src/main/resources/Dockerfile.builder --tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/mycloudlab/escriba-server:latest .
          docker tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/mycloudlab/escriba-server:latest ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/mycloudlab/escriba-server:${{ steps.get_tag_name.outputs.VERSION }}
          docker push ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/mycloudlab/escriba-server
